//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("3.2.0")]
[assembly: System.Reflection.AssemblyFileVersion("3.2.0.29833")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.2.0")]


